djangoseller/source_code/main/urls.py
from django.conf.urls import url, patterns

import views

urlpatterns = patterns('',
    url(r'^$', views.HomeView.as_view(), name='index')
) 

djangoseller/source_code/products/urls.py
from django.conf.urls import url, patterns
from rest_framework.urlpatterns import format_suffix_patterns

import views

from .forms import *

urlpatterns = patterns('',
    url(r'^1/list', views.ProductListView.as_view(filter_form_class=ShirtFilterForm), name='shirts-list'),
    url(r'^2/list', views.ProductListView.as_view(filter_form_class=PantsFilterForm)),
    url(r'^4/list', views.ProductListView.as_view(filter_form_class=ShortsFilterForm)),
    url(r'^5/list', views.ProductListView.as_view(filter_form_class=LongSleeveFilterForm)),
    url(r'^6/list', views.ProductListView.as_view(filter_form_class=HatsFilterForm)),
    url(r'^7/list', views.ProductListView.as_view(filter_form_class=ShoesFilterForm)),
    url(r'^list', views.ProductListView.as_view(), name='list'),
    url(r'^detail/(?P<pk>[0-9]+)$', views.ProductDetailView.as_view(), name='detail'),
    url(r'^api/list', views.ProductListAPI.as_view(), name='api_list')
) 

urlpatterns = format_suffix_patterns(urlpatterns, allowed=['json'])

djangoseller/source_code/seller/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', include('main.urls', namespace='main')),
    url(r'^products/', include('products.urls', namespace='products')),
    url(r'^carts/', include('carts.urls', namespace='carts')),
    url(r'^checkout/', include('checkout.urls', namespace='checkout')),
    url(r'^users/', include('users.urls', namespace='users')),
    url(r'^account/', include('account.urls', namespace='account')),
    url(r'^orders/', include('orders.urls', namespace='orders')),
    url(r'^reviews/', include('reviews.urls', namespace='reviews')),
    url(r'^office/', include('office.urls', namespace='office')),
)

djangoseller/source_code/main/models.py
from django.db import models

# Create your models here.

djangoseller/source_code/main/views.py
from django.shortcuts import render

from django.views.generic import TemplateView

class HomeView(TemplateView):
    template_name = 'main/index.html'

djangoseller/source_code/main/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<head>
<title>{% block title %}Seller{% endblock title %}</title>
<link rel="stylesheet" href="{% static 'css/main.css' %}"/>
<link rel="stylesheet" href="{% static 'css/mango.css' %}"/>
<script src="{% static 'bower_components/jquery/dist/jquery.js' %}"></script>
<script src="{% static 'bower_components/angular/angular.js' %}"></script>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
{% block head_tags %}
{% endblock head_tags %}
</head>
<body class="mango-body">
   <div id="main_navigation" class="horinav">
   <label for="menu" class="mango-menu-label">Menu</label>
   <input id="menu" class="mango-menu-toggle" type="checkbox"/>
   <ul>
      <li><a href="{% url 'main:index' %}">Home</a></li>
      <li><a href="{% url 'products:shirts-list' %}">Shop</a></li>
      <li><a href="{% url 'carts:detail' %}">Cart</a></li>
      <li><a href="{% url 'account:index' %}">Account</a>
          <!--<ul>
            <li><a href="#">test</a></li>
            <li><a href="#">test</a></li> 
            <li><a href="#">test</a></li>
            <li><a href="#">test</a></li>
          </ul>-->
      </li>
      <li><a href="{% url 'users:signup' %}">Sign up</a></li>
      <li><a href="{% url 'users:signin' %}">Sign in</a></li>
      <li><a href="{% url 'users:signout' %}">Sign out</a></li>
   </ul>
   </div>
<div class="mango-container">
  {% block content %}
  {% endblock content %}
  <footer>
    <h4>About This Site</h4>
    <p><a href="http://giovannicode.com">Author's site (needs updating)</a><p>
    <p><a href="https://github.com/giovannicode/djangoseller">Source code</a><p>
  </footer>
</div>
</body>
</html>