djangoseller/source_code/main/urls.py
from django.conf.urls import url, patterns

import views

urlpatterns = patterns('',
    url(r'^$', views.HomeView.as_view(), name='index')
) 

djangoseller/source_code/products/urls.py
from django.conf.urls import url, patterns
from rest_framework.urlpatterns import format_suffix_patterns

import views

from .forms import *

urlpatterns = patterns('',
    url(r'^1/list', views.ProductListView.as_view(filter_form_class=ShirtFilterForm), name='shirts-list'),
    url(r'^2/list', views.ProductListView.as_view(filter_form_class=PantsFilterForm)),
    url(r'^4/list', views.ProductListView.as_view(filter_form_class=ShortsFilterForm)),
    url(r'^5/list', views.ProductListView.as_view(filter_form_class=LongSleeveFilterForm)),
    url(r'^6/list', views.ProductListView.as_view(filter_form_class=HatsFilterForm)),
    url(r'^7/list', views.ProductListView.as_view(filter_form_class=ShoesFilterForm)),
    url(r'^list', views.ProductListView.as_view(), name='list'),
    url(r'^detail/(?P<pk>[0-9]+)$', views.ProductDetailView.as_view(), name='detail'),
    url(r'^api/list', views.ProductListAPI.as_view(), name='api_list')
) 

urlpatterns = format_suffix_patterns(urlpatterns, allowed=['json'])

djangoseller/source_code/reviews/urls.py
from django.conf.urls import url, patterns

import views

urlpatterns = patterns('',
    url(r'^create/(?P<product_id>[0-9]+)$', views.ReviewCreateView.as_view(), name='create'),
    url(r'^list/(?P<product_id>[0-9]+)$', views.ReviewListView.as_view(), name='list'),
)

djangoseller/source_code/seller/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', include('main.urls', namespace='main')),
    url(r'^products/', include('products.urls', namespace='products')),
    url(r'^carts/', include('carts.urls', namespace='carts')),
    url(r'^checkout/', include('checkout.urls', namespace='checkout')),
    url(r'^users/', include('users.urls', namespace='users')),
    url(r'^account/', include('account.urls', namespace='account')),
    url(r'^orders/', include('orders.urls', namespace='orders')),
    url(r'^reviews/', include('reviews.urls', namespace='reviews')),
    url(r'^office/', include('office.urls', namespace='office')),
)

djangoseller/source_code/products/models.py
from django.db import models
from django.core.urlresolvers import reverse
from categories.models import Category

class Tag(models.Model):
    category = models.ForeignKey(Category)
    name = models.CharField(max_length='30')
    value = models.CharField(max_length='30')

    def __unicode__(self):
        return '[' + self.category.name + '] - ' + self.name + ': ' + self.value


class Product(models.Model):
    name = models.CharField(max_length=60)
    description = models.CharField(max_length=255)
    picture = models.ImageField(upload_to='products')
    price = models.DecimalField(max_digits=14, decimal_places=2)
    qty = models.PositiveIntegerField()

    COLOR_CHOICES = (
        ('red', 'red'),
        ('orange', 'orange'),
        ('yellow', 'yellow'),
        ('green', 'green'),
        ('cyan', 'cyan'),
        ('blue', 'blue'), 
        ('purple', 'purple'),
        ('pink', 'pink'),
        ('brown', 'brown'),
        ('gold', 'gold'),
        ('black', 'black'),
        ('gray', 'gray'),
        ('white', 'white')
    )
    color = models.CharField(max_length=30, choices=COLOR_CHOICES) 
    categories = models.ManyToManyField(Category)
    tags = models.ManyToManyField(Tag)
   
    class Meta:
        ordering = ['price']
    
    def get_absolute_url(self):
        return reverse('products:detail', args=[str(self.id)])

    def __unicode__(self):
        return self.name

djangoseller/source_code/products/forms.py
from django import forms

from .models import Product, Tag

class TagChoiceField(forms.ModelChoiceField):

    def __init__(self, *args, **kwargs):
        kwargs.setdefault('empty_label', 'Any')
        super(TagChoiceField, self).__init__(*args, **kwargs)

    def label_from_instance(self, obj):
        return obj.value

class FilterForm(forms.Form):
    color = forms.ChoiceField(choices=Product.COLOR_CHOICES)


class ShirtFilterForm(forms.Form):

    def __init__(self, *args, **kwargs):
        kwargs.setdefault('label_suffix', '')
        super(ShirtFilterForm, self).__init__(*args, **kwargs)

    color = TagChoiceField(queryset=Tag.objects.filter(name='color'))
    use_type = TagChoiceField(queryset=Tag.objects.filter(category__name='t-shirts', name='type'))
    style = TagChoiceField(queryset=Tag.objects.filter(category__name='t-shirts', name='style'))
    fit = TagChoiceField(queryset=Tag.objects.filter(category__name='t-shirts', name='fit'))


class LongSleeveFilterForm(forms.Form):
    color = TagChoiceField(queryset=Tag.objects.filter(name='color'))
    use_type = TagChoiceField(queryset=Tag.objects.filter(category__name='long-sleeves shirts', name='type'))
    style = TagChoiceField(queryset=Tag.objects.filter(category__name='long-sleeves shirts', name='style'))
    fit = TagChoiceField(queryset=Tag.objects.filter(category__name='long-sleeves shirts', name='fit'))
    pattern = TagChoiceField(queryset=Tag.objects.filter(category__name='long-sleeves shirts', name='pattern'))


class ShortsFilterForm(forms.Form):
    color = TagChoiceField(queryset=Tag.objects.filter(name='color'))
    use_type = TagChoiceField(queryset=Tag.objects.filter(category__name='shorts', name='type'))
    length = TagChoiceField(queryset=Tag.objects.filter(category__name='shorts', name='length'))
    pattern = TagChoiceField(queryset=Tag.objects.filter(category__name='shorts', name='pattern'))


class PantsFilterForm(forms.Form):
    color = TagChoiceField(queryset=Tag.objects.filter(name='color'))
    use_type = TagChoiceField(queryset=Tag.objects.filter(category__name='pants', name='type')) 
    fit = TagChoiceField(queryset=Tag.objects.filter(category__name='pants', name='fit'))


class ShoesFilterForm(forms.Form):
    color = TagChoiceField(queryset=Tag.objects.filter(name='color'))
    use_type = TagChoiceField(queryset=Tag.objects.filter(category__name='shoes', name='type'))
    

class HatsFilterForm(forms.Form):
    color = TagChoiceField(queryset=Tag.objects.filter(name='color'))
    style = TagChoiceField(queryset=Tag.objects.filter(category__name='hats', name='style'))

djangoseller/source_code/products/views.py
from django.views.generic import DetailView, ListView
from rest_framework import generics, filters

import django_filters

from .models import Product
from .forms import FilterForm, ShirtFilterForm
from .serializers import ProductSerializer
from categories.models import Category

class ProductListView(ListView):
    model = Product
    filter_form_class = ShirtFilterForm
       
    def get_context_data(self, **kwargs):
        context = super(ProductListView, self).get_context_data(**kwargs)
        context['category_list'] = Category.objects.exclude(name='All')
        context['filter_form'] = self.filter_form_class() 
        return context


class ProductDetailView(DetailView):
    model = Product
    

# API Views.
class ProductListAPI(generics.ListAPIView):
    queryset = Product.objects.all()
    serializer_class = ProductSerializer

    filter_fields = ('name', 'price', 'categories', 'color', 'tags')
    filter_backends = (filters.DjangoFilterBackend, filters.OrderingFilter,)
    ordering_fields = ('price', 'color')

    def get_queryset(self):
        queryset = Product.objects.all()
        tags = self.request.QUERY_PARAMS.getlist('tags')
        #queryset = queryset.filter(tags__in=tags)

        for tag in tags:
            queryset = queryset.filter(tags=tag)
        return queryset
        
    #renderer_classes = [JSONRenderer]

djangoseller/source_code/products/templates/products/product_detail.html
{% extends 'base.html' %}
{% block content %}
    <div>
    <h3>{{ product.name }}</h3>
    <div style="height:200px; width:200px; background-color: {{ product.color }}"></div>
    <p>{{ product.description }}</p>
    <p>{{ product.price }}</p>
    <button class="cart_adder" data-product_id="{{ product.id }}">Add to Cart</button>    
    <a href="{% url 'reviews:create' product_id=product.id %}"><button> Write a review for {{ product.id }}</button></a>
      <a href="{% url 'reviews:list' product_id=product.id %}">Reviews</a>
    </div>
<script>
$('.cart_adder').click(function(event){
   $.get(
      "/carts/add?product_id=" + $(this).data('product_id'),
      function(data){
          alert(data);
      }
   )
   .fail(function(){ 
      alert("I'm sorry and error occured.");
   });
});
</script>
{% endblock content %}

djangoseller/source_code/products/templates/products/product_list.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block head_tags %}
<script src="{% static 'products/js/ctrl.js' %}"></script>
{% endblock head_tags %}

{% block content %}
    <div id="category_nav" class="vertinav">
        <ul>
        {% for category in category_list %}
            <li><a href="/products/{{category.id}}/list">{{ category.name|capfirst }}</a></li>
        {% endfor %}
        </ul>
    </div>
    <div class="mango-grid" id="products_app" ng-app="productsApp">
        <div id="productsController" ng-controller="productsController">
            <form class="mango-form-horizontal">
                <p>
                    <label for="q">Sort By</label>
                    <select id="id_ordering" name="ordering">
                        <option value="price">Low to High</option>
                        <option value="-price">High to Low</option>
                    </select>
                </p>
                {{ filter_form.as_p }}
            </form>
            <script>
   window.onload = function(){
       $('#id_color').on('focus', function(){
           previous_color = this.value;
       }).change(function(){
           angular.element('#productsController').scope().update_tagurl($(this).val(), previous_color);
           previous_color = this.value;
       })
       
       $('#id_style').on('focus', function(){
           previous_style = this.value;
       }).change(function(){
           angular.element('#productsController').scope().update_tagurl($(this).val(), previous_style);
           previous_style = this.value;
       })
   
       $('#id_fit').on('focus', function(){ 
           previous_fit = this.value;
       }).change(function(){
           angular.element('#productsController').scope().update_tagurl($(this).val(), previous_fit);
           previous_fit = this.value;
       })

       $('#id_use_type').on('focus', function(){ 
           previous_use_type = this.value;
       }).change(function(){ 
           angular.element('#productsController').scope().update_tagurl($(this).val(), previous_use_type);
           previous_use_type = this.value;
           
       })

       $('#id_ordering').change(function(){
           angular.element('#productsController').scope().update_filterurl($(this).attr('name'), $(this).val());
       })
   }
var anchor = function(url){
  alert(url);
}
            </script>
            <div class="products_box">
                <div class="mango-grid-box product_box" ng-repeat="product in data track by $index">
                    <a href="" ng-click="goto(product.absolute_url)">
                      <div style="height:200px; width:200px; background-color: {[{product.color}]}"></div>
                      <!--<img width="200px" height="200px" id="{[{product.pk}]}" src="/media/{[{product.picture}]}"/>-->
                    </a>
                    <p>{[{ product.name }]}</p>
                    <p>{[{ product.description }]}</p>
                    <p>{[{ product.price }]}</p>
                    <button class="cart_adder" ng-click="add_to_cart(product.id, '{{ csrf_token }}')">Add to Cart</button>
                </div>
            </div>
        </div>
    </div>

<script>
$('.cart_adder').click(function(event){
   $.post(
      "{% url 'carts:add' %}",
      {
         product_id: $(this).data('product_id'),
         csrfmiddlewaretoken: '{{ csrf_token }}'
      },
      function(data){
          alert(data);
      }
   )
   .fail(function(){ 
      alert("I'm sorry and error occured.");
   });
});

</script>
{% endblock content %}