djangoseller/source_code/main/urls.py
from django.conf.urls import url, patterns

import views

urlpatterns = patterns('',
    url(r'^$', views.HomeView.as_view(), name='index')
) 

djangoseller/source_code/orders/urls.py
from django.conf.urls import url, patterns
import views

urlpatterns = patterns('',
    url(r'^$', views.OrderListView.as_view(), name='index'),
    url(r'^detail/(?P<pk>[0-9]+)$', views.OrderDetailView.as_view(), name='detail'),
)

djangoseller/source_code/orders/models.py
from django.db import models
from django.conf import settings
from django.core.mail import send_mail
from django.core.urlresolvers import reverse

from products.models import Product
from payments.models import Payment


class Address(models.Model):
    street = models.CharField(max_length=60)
    city = models.CharField(max_length=60)
    state = models.CharField(max_length=2)
    zipcode = models.CharField(max_length=5) 

    def __unicode__(self):
        return "{street}, {city}, {state}, {zipcode}".format(
            street=self.street,
            city=self.city,
            state=self.state,
            zipcode=self.zipcode
        )


class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, null=True)
    email = models.EmailField()
    date = models.DateTimeField(auto_now_add=True)
    payment = models.OneToOneField(Payment)
    address = models.OneToOneField(Address)
    shipped = models.BooleanField(default=False)

    def get_absolute_url(self):
        return reverse('orders:detail', args=[str(self.id)])

    def __unicode__(self):
        return "Order ID: {id}, Email: {email}, Shipped: {shipped}"\
               .format(id=self.id, email=self.email, shipped=self.shipped)

    def save(self, *args,**kwargs):
        if self.pk is not None:
           orig = Order.objects.get(pk=self.pk)
           if orig.shipped == False and self.shipped == True:
               send_mail(
                   'Your order has been shipped',
                   'Hi ' + self.user.first_name + ', we though you\'d like to know that you order has been shipped',
                   'sales@djangoseller.com',
                   [self.email],
                   fail_silently=False
               )
        super(Order, self).save(*args, **kwargs)
                    

class OrderItem(models.Model):
    order = models.ForeignKey(Order)
    product = models.ForeignKey(Product)
    title = models.CharField(max_length=60)
    price = models.DecimalField(max_digits=14, decimal_places=2)
    qty = models.PositiveIntegerField() 

djangoseller/source_code/orders/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView

from .models import Order


class OrderListView(ListView):
    model = Order

    def get_queryset(self):
        user = self.request.user
        return user.order_set.all().order_by('-date')

class OrderDetailView(DetailView):
    model = Order

    def get_queryset(self):
        queryset = super(OrderDetailView, self).get_queryset()
        return queryset.filter(user=self.request.user)

djangoseller/source_code/orders/templates/orders/order_detail.html
{% extends 'base.html' %}
{% block content %}
   
<div>
    <p><b>Order ID: </b>{{ order.id }}</p>
    <p><b>Order Date: </b>{{ order.date }}</p>
<table>
    <tr><th><b>Items Ordered</b></th></tr>
{% for order_item in order.orderitem_set.all %}
    <tr><td>{{ order_item.title }}</td><td>{{ order_item.price }}</td><td>{{ order_item.qty }}</td></tr>
{% endfor %}
</table>
<p><b>Order Total: </b>{{ order.payment.total }}</p>
<p><b>Ship Items to: </b>{{ order.address }}</p>
</div>
{% endblock content %}

djangoseller/source_code/orders/templates/orders/order_list.html
{% extends 'base.html' %}

{% block content %}
  {% for order in order_list %}
  <div>
    <p>{{ order.id }}</p>
    <p>{{ order.date }}</p>
    <p>{{ order.payment.total }}</p>
    <a href="{{ order.get_absolute_url }}">View Order</a>
  </div>
  {% endfor %}
{% endblock content %}