djangoseller/source_code/main/urls.py
from django.conf.urls import url, patterns

import views

urlpatterns = patterns('',
    url(r'^$', views.HomeView.as_view(), name='index')
) 

djangoseller/source_code/office/urls.py
from django.conf.urls import url, patterns
from rest_framework.urlpatterns import format_suffix_patterns

import views

urlpatterns = patterns('',
    url(r'^$', views.DashboardView.as_view(), name='index'),
    url(r'^login', views.AdminLoginView.as_view(), name='login'),
    url(r'^orders/list', views.OrderListView.as_view(), name='order_list')
)

urlpatterns = format_suffix_patterns(urlpatterns, allowed=['json'])

djangoseller/source_code/seller/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', include('main.urls', namespace='main')),
    url(r'^products/', include('products.urls', namespace='products')),
    url(r'^carts/', include('carts.urls', namespace='carts')),
    url(r'^checkout/', include('checkout.urls', namespace='checkout')),
    url(r'^users/', include('users.urls', namespace='users')),
    url(r'^account/', include('account.urls', namespace='account')),
    url(r'^orders/', include('orders.urls', namespace='orders')),
    url(r'^reviews/', include('reviews.urls', namespace='reviews')),
    url(r'^office/', include('office.urls', namespace='office')),
)

djangoseller/source_code/office/models.py
from django.db import models

# Create your models here.

djangoseller/source_code/office/views.py
from django.contrib.auth import login
from django.shortcuts import render, redirect
from django.views.generic import ListView, FormView, TemplateView
from django.contrib.admin.forms import AdminAuthenticationForm

from braces.views import AnonymousRequiredMixin, StaffuserRequiredMixin

from rest_framework import generics, serializers

from orders.models import Order

class AdminLoginView(AnonymousRequiredMixin, FormView):
    authenticated_redirect_url = u"/"
    template_name = 'office/login.html'
    form_class = AdminAuthenticationForm

    def form_valid(self, form):
        login(self.request, form.get_user())
        return redirect('office:index')

class DashboardView(StaffuserRequiredMixin, TemplateView):
    template_name = u"office/index.html"


class OrderSerializer(serializers.ModelSerializer):
    class Meta:
        model = Order


class OrderListView(ListView):
    model = Order
    template_name = 'office/object_list.html'


class OrderOffice(generics.ListAPIView): 
    model = Order
    serializer_class = OrderSerializer
    queryset = Order.objects.all()

djangoseller/source_code/office/templates/office/base.html
{% load staticfiles %}
<!DOCTYPE html>
<head>
   <title>{% block title %}Seller{% endblock title %}</title>
   <link rel="stylesheet" href="{% static 'css/mango.css' %}"/>
   <script src="{% static 'bower_components/jquery/dist/jquery.js' %}"></script>
   <meta charset="utf-8">
   <meta name="viewport" content="width=device-width, initial-scale=1">
   {% block head_tags %}
   {% endblock head_tags %}
</head>
<body>
   {% block content %}
   {% endblock content %}
</body>
</html>

djangoseller/source_code/office/templates/office/index.html
{% extends 'office/base.html' %}

{% block content %}
   <a href="{% url 'office:order_list' %}">Manage Orders</a>
{% endblock content %}

djangoseller/source_code/office/templates/office/login.html
{% extends 'office/base.html' %}

{% block content %}
   <form method="POST"> 
      {% csrf_token %}
      {{ form.as_p }}
      <input type="submit" value="submit"/>
   </form>
{% endblock content %}

djangoseller/source_code/office/templates/office/object_list.html
{% extends 'office/base.html' %}

{% block head_tags %}

{% endblock head_tags %}

{% block content %}
   {% for order in order_list %}
      <div>{{ order.payment.total }}</div>
   {% endfor %}
{% endblock content %}